#如果有别的插件依赖本插件，从而不想用本插件的命令伪装的话可以把下方项改为 false
开启原功能: true
#扒拉下伪装/如果关闭就会导致右键伪装模型不做任何事情
扒拉伪装: true
#字面意思,一种精灵抓多少次才能伪装成它
每种精灵抓多少次才能伪装: 5
#1秒为20tick上方单位是tick
伪装更新: 5
#允许伪装的世界/如果有附属插件,这个限制是限制不住的
世界配置:
  #关闭则不限制世界伪装
  启用: true
  worlds:
    - 'world'
#玩家数据可以不用管
玩家数据:
  GSQ_Lin:
    可伪装:
      - 'Abomasnow'
    记录:
      - 'Absol'
      - 'Absol'
      - 'Absol'
      - 'Absol'